[package]
name = "rBittorrent"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde = {version = "1.0.219", features = ["derive"]}
serde_bencode = "0.2.4"
serde_bytes = "0.11"
sha1 = "0.10.6"
